### PR TITLE
Update style.css

### PR DESCRIPTION
**Pull request by khadija12321**
Improving Header and add transition

### CODE REVIEW

**Comment by khadija12321** [comment]
Improving header and Transition

**Comment by khadija12321** [comment]
This pull request brings in substantial changes to the CSS Visual Learner tool, primarily focusing on the full-width implementation and the transition effects. Here's a revised version of your description:
### Header

- The header now spans the full width of the page.
- Text alignment is set to center.
- No top margin is applied.

### Transition

- A smooth transition effect has been incorporated into the boxes.
- Each box now visualizes its properties within one second.

**Comment by fahdi** [comment]
@khadija12321 Update the original PR and open it again. This one was closed.

**Comment by fahdi** [comment]
Also, I don't see any Screenshots in the PR description.

**Comment by fahdi** [comment]
And also, name your branches properly. Patch 7 doesn't mean anything.

**Comment by fahdi** [comment]
And also, your commit messages don't mean anything. Please look at previous commit messages to see what I mean.

**Pull request closed without merging**
