### PR TITLE
Update style.css

### PR DESCRIPTION
**Pull request by khadija12321**
This pull request brings in substantial changes to the CSS Visual Learner tool, primarily focusing on the full-width implementation and the transition effects. Here's a revised version of your description:

### Header
**Key Features:**

The header now spans the full width of the page.
Text alignment is set to center.
No top margin is applied.
Transition
A smooth transition effect has been incorporated into the boxes. Each box now visualizes its properties within one second.

**This screenshot of Header changes:**

**This screenshot of Transition added in flexbox:**

### CODE REVIEW

**Comment by fahdi** [comment]
@khadija12321 Why would I want a screenshot of the code? Show what this code does!

**Comment by khadija12321** [comment]
This code complete the width of header and text will align center.
1s transition have added in boxes when they work on their then they take a time of 1s  to change their visualization.

**Comment by fahdi** [comment]
Please read my comment again. I am asking for sharing a screenshot of your **changes**, not your code changes.

**Comment by khadija12321** [comment]
I do it changes on GitHub not a locally.

**Comment by fahdi** [comment]
You are supposed to test changes. Do not do them randomly.

**Comment by khadija12321** [comment]
Ok, I will do it.

**Pull request closed without merging**
